# Generated by Django 3.0.6 on 2020-05-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TurtleMasterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionDataUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_state', models.TextField(blank=True, null=True)),
                ('country_region', models.TextField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('incident_rate', models.FloatField(blank=True, null=True)),
                ('people_tested', models.IntegerField(blank=True, null=True)),
                ('people_hospitalized', models.IntegerField(blank=True, null=True)),
                ('mortality_rate', models.FloatField(blank=True, null=True)),
                ('uid', models.BigIntegerField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('testing_rate', models.FloatField(blank=True, null=True)),
                ('hospitalization_rate', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'infection_data_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfectionDataUsStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_state', models.TextField(blank=True, null=True, unique=True)),
                ('country_region', models.TextField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('incident_rate', models.FloatField(blank=True, null=True)),
                ('people_tested', models.IntegerField(blank=True, null=True)),
                ('people_hospitalized', models.IntegerField(blank=True, null=True)),
                ('mortality_rate', models.FloatField(blank=True, null=True)),
                ('uid', models.BigIntegerField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('testing_rate', models.FloatField(blank=True, null=True)),
                ('hospitalization_rate', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'infection_data_us_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfectionDataWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('admin2', models.TextField(blank=True, null=True)),
                ('province_state', models.TextField(blank=True, null=True)),
                ('country_region', models.TextField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('combined_key', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'infection_data_world',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InfectionDataWorldStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fips', models.IntegerField(blank=True, null=True)),
                ('admin2', models.TextField(blank=True, null=True)),
                ('province_state', models.TextField(blank=True, null=True, unique=True)),
                ('country_region', models.TextField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField(blank=True, null=True)),
                ('combined_key', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'infection_data_world_statistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesDataUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(blank=True, null=True)),
                ('iso2', models.TextField(blank=True, null=True)),
                ('iso3', models.TextField(blank=True, null=True)),
                ('code3', models.IntegerField(blank=True, null=True)),
                ('admin2', models.TextField(blank=True, null=True)),
                ('combined_key', models.TextField(blank=True, null=True)),
                ('province_state', models.TextField(blank=True, null=True)),
                ('country_region', models.TextField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_series_data_us',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeSeriesDataWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_state', models.TextField(blank=True, null=True)),
                ('country_region', models.TextField(blank=True, null=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'time_series_data_world',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ViewStatisticsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_region', models.TextField(blank=True, null=True, unique=True)),
                ('last_update', models.DateField(blank=True, null=True)),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'view_statistics_data',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='entry',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Corona',
        ),
        migrations.DeleteModel(
            name='Entry',
        ),
    ]
